name: ASP
channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- python=3.8
- pytorch>=1.13.0
- torchvision>=0.14.0
- pytorch-cuda=11.8
- scipy
- dominate
- opencv<4
- Pillow
- numpy<2
- visdom
- packaging
- GPUtil
